// src/components/AllEventsView.vue
<script setup>
import { formatDate, formatTime } from '../common/date.js'

defineProps(['events', 'isCurrentView'])
</script>

<template>
  <div id="all-events-view" v-if="isCurrentView">
    <h2>All Events</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Summary</th>
          <th>Starts At</th>
          <th>Ends At</th>
        </tr>
      </thead>
      <tbody>
        <tr class="event" v-for="event in events">
          <td class="summary">
            {{ event.summary }}
          </td>
          <td class="starts_at">
            {{ formatDate(event.starts_at) }} {{ formatTime(event.starts_at) }}
          </td>
          <td class="ends_at">
            {{ formatDate(event.ends_at) }} {{ formatTime(event.ends_at) }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// react/src/components/AllEventsView.tsx
'use client'

import { formatDateTime } from '../common/dates.js'

interface Event {
  id: number,
  summary: string,
  starts_at: Date,
  ends_at: Date
}

export default function AllEventsView({
  events
}: Readonly<{
  events: Event[]
}>) {
  return (
    <div id="all-events-view">
      <div className="container mb-1">
        <div className="row">
          <div className="col">
            <h2 id="current-period">
              All Events
            </h2>
          </div>
          <div className="col text-end">
          </div>
        </div>
      </div>
      <table className="table mx-1">
        <thead>
          <tr>
            <th>Event</th>
            <th>Starts At</th>
            <th>Ends At</th>
          </tr>
        </thead>
        <tbody>
        {events.map((event) => (
          <tr className="event px-1" key={event.id}>
            <td className="summary" width="60%">
              {event.summary}
            </td>
            <td className="starts_at" width="20%">
              {formatDateTime(event.starts_at)}
            </td>
            <td className="ends_at" width="20%">
              {formatDateTime(event.ends_at)}
            </td>
          </tr>
        ))}
        </tbody>
      </table>
    </div>
  )
}
