// src/components/DayView.vue
<script setup>
import { ref, computed } from 'vue'

import {
  dateToday,
  dateFrom,
  dateTimeFrom,
  formatTime,
  formatDateTime,
  formatDayViewHeader
} from '../common/dates.js'

const props = defineProps(['events', 'today', 'isCurrentView'])

const today = ref(props.today)

const header = computed(() => {
  return formatDayViewHeader(today.value)
})

const calendar = computed(() => {
  const calendar = []

  for (let h = 0; h < 24; h++) {
    const date = dateTimeFrom(today.value, h)

    calendar.push(date.toISOString())
  }

  return calendar
})

function prevDay() {
  today.value = dateFrom(today.value, -1)
}

function thisDay() {
  today.value = dateToday()
}

function nextDay() {
  today.value = dateFrom(today.value, 1)
}
</script>

<template>
  <div id="day-view" v-if="isCurrentView">
    <div class="container">
      <div class="row">
        <div class="col">
          <h2 class="current-period" data-test="header">
            {{ header }}
          </h2>
        </div>
        <div class="col text-end">
          <a id="prev-day" href="#" @click="prevDay">&lt; Prev</a>
          <a id="this-day" class="mx-1" href="#" @click="thisDay">Today</a>
          <a id="next-day" href="#" @click="nextDay">Next &gt;</a>
        </div>
      </div>
    </div>
    <div id="day" class="container">
      <div class="row" v-for="dateTime in calendar">
        <div class="col-1 border text-end">{{ formatTime(dateTime) }}</div>
        <div class="col border">
          <div class="row">
            <div class="col event"
                 :class="dateTime"
                 v-for="event in events[dateTime]"
                 data-test="event">
              <span class="summary">
                {{ event.summary }}
              </span>
              <span class="starts_at visually-hidden">
                {{ formatDateTime(event.starts_at) }}
              </span>
              <span class="ends_at visually-hidden">
                {{ formatDateTime(event.ends_at) }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// react/src/components/DayView.tsx
import { useState } from 'react'

import { dateFrom, formatTime, formatDateTime, formatDayViewHeader } from '../common/dates.js'
import { dayCalendar } from '../common/calendars.js'

interface Event {
  id: number,
  summary: string,
  starts_at: string,
  ends_at: string
}

export default function DayView({
  events,
  today
}: Readonly<{
  events: { [key: string]: Event[] },
  today: Date
}>) {
  const [currentDate, setCurrentDate] = useState(today)

  const calendar = dayCalendar(currentDate)

  function prevDay() {
    setCurrentDate(dateFrom(currentDate, -1))
  }

  function nextDay() {
    setCurrentDate(dateFrom(currentDate, 1))
  }

  return (
    <div id="day-view">
      <div className="container mb-1">
        <div className="row">
          <div className="col">
            <h2 id="current-period">
              {formatDayViewHeader(currentDate)}
            </h2>
          </div>
          <div className="col text-end">
            <div className="btn-group"
                 role="group">
              <button id="prev-period"
                      type="button"
                      className="btn btn-sm btn-outline-secondary px-2"
                      onClick={prevDay}>
                ◀
              </button>
              <button id="this-period"
                      type="button"
                      className="btn btn-sm btn-outline-secondary">
                Today
              </button>
              <button id="next-period"
                      type="button"
                      className="btn btn-sm btn-outline-secondary"
                      onClick={nextDay}>
                ▶
              </button>
            </div>
          </div>
        </div>
      </div>
      <div id="day" className="container">
      {calendar.map((dateTime) => (
        <div className="row event-row"
             key={dateTime}>
          <div className="col-1 border text-end">
            {formatTime(dateTime)}
          </div>
          <div className="col border">
            <div className="position-relative row">
            {(events[dateTime] ?? []).map((event) => (
              <div className="position-absolute col event border border-primary bg-primary-subtle bg-gradient px-1"
                   key={event.id}>
                <div className="hour">
                  {formatTime(event.starts_at)}
                </div>
                <div className="summary">
                  <strong>{event.summary}</strong>
                </div>
                <span className="starts_at visually-hidden">
                  {formatDateTime(event.starts_at)}
                </span>
                <span className="ends_at visually-hidden">
                  {formatDateTime(event.ends_at)}
                </span>
              </div>
            ))}
            </div>
          </div>
        </div>
      ))}
      </div>
    </div>
  )
}
