// app/src/components/Event.vue
<script setup>
import { formatDateTime } from '../common/dates.js'

defineProps(['event'])
</script>

<template>
  <div class="col event border border-primary bg-primary-subtle bg-gradient px-1">
    <span class="summary">
      {{ event.summary }}
    </span>
    <span class="starts_at visually-hidden">
      {{ formatDateTime(event.starts_at) }}
    </span>
    <span class="ends_at visually-hidden">
      {{ formatDateTime(event.ends_at) }}
    </span>
  </div>
</template>

// react/src/components/Event.tsx
import { formatTime, formatDateTime } from '../common/dates.js'

interface Event {
  id: number,
  summary: string,
  starts_at: string,
  ends_at: string
}

export default function Event({
  event
} : Readonly<{
  event: Event
}>) {
  return (
    <div className="position-absolute col event border border-primary bg-primary-subtle bg-gradient px-1">
      <div className="hour">
        {formatTime(event.starts_at)}
      </div>
      <div className="summary">
        <strong>{event.summary}</strong>
      </div>
      <span className="starts_at visually-hidden">
        {formatDateTime(event.starts_at)}
      </span>
      <span className="ends_at visually-hidden">
        {formatDateTime(event.ends_at)}
      </span>
    </div>
  )
}
