// app/src/components/ViewHeader.vue
<script setup>
defineProps(['header', 'prevAction', 'thisAction', 'nextAction'])
</script>

<template>
  <div class="container mb-1">
    <div class="row">
      <div class="col">
        <h2 id="current-period">
          {{ header }}
        </h2>
      </div>
      <div class="col text-end">
        <div class="btn-group"
             role="group"
             aria="Calendar Navigation"
             v-if="thisAction">
          <button id="prev-period"
                  type="button"
                  class="btn btn-sm btn-outline-secondary px-2"
                  @click="prevAction">
            ◀
          </button>
          <button id="this-period"
                  type="button"
                  class="btn btn-sm btn-outline-secondary"
                  @click="thisAction">
            Today
          </button>
          <button id="next-period"
                  type="button"
                  class="btn btn-sm btn-outline-secondary"
                  @click="nextAction">
            ▶
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// react/src/components/ViewHeader.tsx
export default function ViewHeader({
  header,
  prevAction,
  thisAction,
  nextAction
} : {
  header: string,
  prevAction: React.MouseEventHandler,
  thisAction: React.MouseEventHandler,
  nextAction: React.MouseEventHandler
}) {
  return (
    <div className="container mb-1">
      <div className="row">
        <div className="col">
          <h2 id="current-period">
            {header}
          </h2>
        </div>
        <div className="col text-end">
          <div className="btn-group"
               role="group">
            <button id="prev-period"
                    type="button"
                    className="btn btn-sm btn-outline-secondary px-2"
                    onClick={prevAction}>
              ◀
            </button>
            <button id="this-period"
                    type="button"
                    className="btn btn-sm btn-outline-secondary"
                    onClick={thisAction}>
              Today
            </button>
            <button id="next-period"
                    type="button"
                    className="btn btn-sm btn-outline-secondary"
                    onClick={nextAction}>
              ▶
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
