// src/components/WeekView.vue
<script setup>
import { ref, computed } from 'vue'

import {
  dateToday,
  dateTimeKey,
  dateTimeFrom,
  weekStart,
  weekFrom,
  formatTime,
  formatDateTime,
  formatDay,
  formatMonthViewHeader
} from '../common/dates.js'

const props = defineProps(['events', 'today', 'isCurrentView'])

const today = ref(props.today)

const header = computed(() => {
  return formatMonthViewHeader(today.value)
})

const calendar = computed(() => {
  const calendar = []

  const startDate = weekStart(today.value)

  for (let h = 0; h < 24; h++) {
    const hour = []

    for (let d = 0; d < 7; d++) {
      const date = dateTimeFrom(startDate, ((d * 24) + h))

      hour.push(dateTimeKey(date))
    }

    calendar.push(hour)
  }

  return calendar
})

const days = computed(() => {
  const date = calendar.value[0]

  return {
    'Sun': formatDay(date[0]),
    'Mon': formatDay(date[1]),
    'Tue': formatDay(date[2]),
    'Wed': formatDay(date[3]),
    'Thu': formatDay(date[4]),
    'Fri': formatDay(date[5]),
    'Sat': formatDay(date[6])
  }
})

function prevWeek() {
  today.value = weekFrom(today.value, -1)
}

function thisWeek() {
  today.value = dateToday()
}

function nextWeek() {
  today.value = weekFrom(today.value, 1)
}
</script>

<template>
  <div id="week-view" v-if="isCurrentView">
    <div class="container">
      <div class="row">
        <div class="col">
          <h2 class="current-period" data-test="header">
            {{ header }}
          </h2>
        </div>
        <div class="col text-end">
          <a id="prev-week" href="#" @click="prevWeek">&lt; Prev</a>
          <a id="this-week" class="mx-1" href="#" @click="thisWeek">Today</a>
          <a id="next-week" href="#" @click="nextWeek">Next &gt;</a>
        </div>
      </div>
    </div>
    <div id="week" class="container">
      <div class="row text-center">
        <div class="col">
          &nbsp;
        </div>
        <div class="col" v-for="(value, label) in days">
          <strong>{{ label }}</strong>
          <span class="day ms-1">
            <strong>{{ value }}</strong>
          </span>
        </div>
      </div>
      <div class="row" v-for="hour in calendar">
        <div class="col-1 border text-end">{{ formatTime(hour[0]) }}</div>
        <div class="col border" v-for="dateTime in hour">
          <div class="row">
            <div class="col event"
                 :class="dateTime"
                 v-for="event in events[dateTime]"
                 data-test="event">
              <span class="summary">
                {{ event.summary }}
              </span>
              <span class="starts_at visually-hidden">
                {{ formatDateTime(event.starts_at) }}
              </span>
              <span class="ends_at visually-hidden">
                {{ formatDateTime(event.ends_at) }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// react/src/components/WeekView.tsx
import { useState } from 'react'

import { weekFrom, formatTime, formatDateTime, formatDay, formatMonthViewHeader } from '../common/dates.js'
import { weekCalendar } from '../common/calendars.js'
import ViewHeader from './ViewHeader'

interface Event {
  id: number,
  summary: string,
  starts_at: string,
  ends_at: string
}

export default function WeekView({
  events,
  today
}: Readonly<{
  events: { [key: string]: Event[] },
  today: Date
}>) {
  const [currentDate, setCurrentDate] = useState(today)

  const header = formatMonthViewHeader(currentDate)

  const calendar = weekCalendar(currentDate)

  const days = weekDays(currentDate)

  function weekDays(currentDate: Date) {
    const week = weekCalendar(currentDate)[0]

    return [
      ['Sun', week[0]],
      ['Mon', week[1]],
      ['Tue', week[2]],
      ['Wed', week[3]],
      ['Thu', week[4]],
      ['Fri', week[5]],
      ['Sat', week[6]]
    ]
  }

  function prevWeek() {
    setCurrentDate(weekFrom(currentDate, -1))
  }

  function thisWeek() {
    setCurrentDate(today)
  }

  function nextWeek() {
    setCurrentDate(weekFrom(currentDate, 1))
  }

  return (
    <div id="week-view">
      <ViewHeader header={header}
                  prevAction={prevWeek}
                  thisAction={thisWeek}
                  nextAction={nextWeek} />
      <div id="week" className="container">
        <div className="row text-center">
          <div className="col-1">
            &nbsp;
          </div>
          {days.map(([label, value]) => (
          <div className="col" key={value}>
            <strong>{label}</strong>
            <span className="day ms-1">
              <strong>{formatDay(value)}</strong>
            </span>
          </div>
          ))}
        </div>
        {calendar.map((hour) => (
        <div className="row event-row" key={hour[0]}>
          <div className="col-1 border text-end">
            {formatTime(hour[0])}
          </div>
          {hour.map((dateTime) => (
          <div className="col border" key={dateTime}>
            <div className="position-relative row">
              {(events[dateTime] ?? []).map((event) => (
              <div className="position-absolute col event border border-primary bg-primary-subtle bg-gradient px-1"
                   key={event.id}>
                <div className="hour">
                  {formatTime(event.starts_at)}
                </div>
                <div className="summary">
                  <strong>{event.summary}</strong>
                </div>
                <span className="starts_at visually-hidden">
                  {formatDateTime(event.starts_at)}
                </span>
                <span className="ends_at visually-hidden">
                  {formatDateTime(event.ends_at)}
                </span>
              </div>
              ))}
            </div>
          </div>
          ))}
        </div>
        ))}
      </div>
    </div>
  )
}
